project_id = "wmwuirqdluzjdqtmfzsm"

[functions.generate-verso-resumido]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.generate-study-plan]
verify_jwt = true

[functions.get-public-settings]
verify_jwt = false